name: BE deploy develop branch
run-name: BE deploy develop branch
on:
  push:
    branches:
      - 'develop'
    paths:
    - backend/**
jobs:
  build:
    runs-on: [self-hosted,backend-server-dev]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - run: |
          ls
          echo "Buil image"

  deploy:
    runs-on: [self-hosted,backend-server-dev]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - run: |
          ls
          echo "Run image"