name: FE-CI
run-name: ${{ github.actor }} is validating eslint.

on:
  pull_request:
    branches:
      - 'develop'
      - 'main'
    paths:
        - backend/**
defaults:
  run:
    working-directory: ./backend
jobs:
  validate-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Using docker to check convention code
        run: |
          echo "Start lint...."
          docker run -i --rm -v $(pwd):/app/source -v $(pwd)/.prettierrc:/app/.prettierrc hocptit/eslint-ci:0.0.1 "."
          echo "Lint done."