name: FE-CI
run-name: FE-CI

on:
  pull_request:
    branches:
      - 'develop'
      - 'main'
    paths:
        - frontend/**
defaults:
  run:
    working-directory: ./frontend
jobs:
  validate-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Using docker to check convention code
        run: |
          echo "Start lint...."
          echo "Run demo."
          echo "Lint done."        